Repository bcgov/invasivesbc, pull requests merged in 2020-12, with the labels that each got.

#196 Map Popout Component from the Bottom
  app/src/components/map/MapContainer.tsx
  app/src/features/home/map/MapPage.tsx
Labels: enhancement, frontend

#204 Area type bug
  app/src/features/home/activity/ActivityPage.tsx
Labels: Bug

#205 Fix form validation issue and post failure, also postman tests body
  api/src/openapi/api-doc.json
  app/src/components/activities-list/ActivitiesList.tsx
  testing/integration/postman/InvasivesBC-API-DEV.postman_collection.json
Labels: Bug

#217 Update steps and description for postman tests
  testing/integration/postman/README.md
Labels: documentation

#225 209: Get form and photos into popout component for activities on map
  app/src/components/photo/PhotoContainer.tsx
  app/src/components/points-of-interest/ActivitiesPOI/ActivitiesPOI.tsx
  app/src/features/home/map/MapPage.tsx
Labels: Form, UX/UI, enhancement, frontend

#235 Refactor to reduce duplication - Part 2
  api/src/models/activity.ts
  api/src/models/media.ts
  api/src/models/point-of-interest.ts
  api/src/paths/activity.ts
  api/src/paths/activity/{activityId}.ts
  api/src/paths/media.ts
  api/src/paths/point-of-interest.ts
  api/src/utils/file-utils.ts
Labels: Bug, enhancement

#234 Refactor code to fix duplication - Part 1
  app/src/components/activities-list/ActivityListItem.tsx
  app/src/components/activities-list/ReferenceActivitiesList.tsx
  app/src/components/activities-list/SearchActivitiesList.tsx
Labels: Bug, enhancement

#236 Refactor to reduce duplication - Part 3
  api/src/paths/activity.ts
  api/src/paths/media.ts
  api/src/paths/point-of-interest.ts
Labels: Bug, enhancement

#237 Sonarcloud: Fix a few code smells
  api/src/paths/context/transform.ts
  api/src/paths/points-of-interest.ts
  app/src/components/status/StatusContainer.tsx
  app/src/features/home/HomeLayout.tsx
  app/src/features/home/search/SearchActivityPage.tsx
  app/src/hooks/useInvasivesApi.ts
Labels: Bug, enhancement

#241 🌷 207: Finalize terrestrial plant form
  api/src/openapi/api-doc.json
  api/src/utils/context-queries.ts
  api/test/activity-with-files.json
  api/test/observation-point.json
  api/test/observation-point2.json
  api/test/observation-polygon.json
  app/package.json
  app/src/components/activity/ActivityComponent.tsx
  app/src/components/form/FormContainer.tsx
  app/src/components/map/MapContainer.tsx
  app/src/features/home/activity/ActivityPage.tsx
  app/src/rjsf/business-rules/customValidation.ts
  app/src/rjsf/uiSchema/BaseUISchemaComponents.ts
  app/src/rjsf/uiSchema/UISchemaComponents.ts
  testing/integration/postman/InvasivesBC-API-DEV.postman_collection.json
Labels: API, Form, UX/UI, enhancement, frontend

#244 Dummy update to test action
  README.md
Labels: DevOps

#242 Fix sort order for code tables and dropdown values ordering
  api/src/utils/api-doc-security-filter.ts
  database/src/seeds/03_business_codes.ts
  database/src/seeds/data/invasives/business_codes.csv
Labels: API, Bug, Form

#247 653: Plant Mechanical Treatment Form
  api/src/openapi/api-doc.json
  app/src/rjsf/business-rules/customValidation.ts
  app/src/rjsf/uiSchema/BaseUISchemaComponents.ts
Labels: API, Form, enhancement, frontend

#248 🍒 654: Plant Chemical Treatment Form
  api/src/openapi/api-doc.json
  app/src/features/home/activity/ActivityPage.tsx
  app/src/rjsf/business-rules/customValidation.ts
  app/src/rjsf/uiSchema/BaseUISchemaComponents.ts
  app/src/rjsf/uiSchema/UISchemaComponents.ts
Labels: API, Form, enhancement, frontend

#252 🌩️ Sonarcloud: Refactor to Reduce Duplication
  app/src/components/activities-list/ActivitiesList.tsx
  app/src/components/activities-list/ActivityListDate.tsx
  app/src/components/activities-list/ReferenceActivitiesList.tsx
Labels: enhancement, frontend

#249 🌱 Finalize More Treatment and Observation Forms
  api/src/openapi/api-doc.json
  app/src/rjsf/uiSchema/BaseUISchemaComponents.ts
Labels: API, Form, enhancement, frontend

#253 Remove Unused Code
  api/src/utils/utils.ts
  app/src/utils/FunctionUtils.ts
Labels: enhancement

#254 🧪 255: Chemical Treatment: Herbicide Autopopulate Application Rate Field
  api/src/openapi/api-doc.json
  app/package.json
  app/src/components/form/FormContainer.tsx
  app/src/features/home/activity/ActivityPage.tsx
  app/src/features/home/search/SearchActivityPage.tsx
  app/src/rjsf/business-rules/constants/herbicideApplicationRates.ts
  app/src/rjsf/business-rules/populateCalculatedFields.ts
Labels: API, Form, enhancement, frontend

#258 ✅ ❌ 239: Custom error and success messages for sync activities
  app/src/components/activities-list/ActivitiesList.tsx
  app/src/utils/errorHandling.ts
Labels: Form, enhancement, frontend

#259 194: Add network plugin support
  api/src/paths/activity/{activityId}.ts
  api/src/paths/media.ts
  app/src/App.tsx
  app/src/AppRouter.tsx
  app/src/components/activities-list/ActivitiesList.tsx
  app/src/components/network/NetworkStatusComponent.tsx
  app/src/components/tabs/TabsContainer.tsx
  app/src/contexts/DatabaseChangesContext.tsx
  app/src/contexts/NetworkContext.tsx
  app/src/features/home/HomeLayout.tsx
  app/src/features/home/HomeRouter.tsx
  app/src/layouts/AuthLayout.tsx
  app/src/layouts/PublicLayout.tsx
  app/src/themes/appTheme.ts
  app/src/utils/AppRoute.tsx
  app/src/utils/PrivateRoute.tsx
Labels: enhancement, frontend, keycloak

#257 ✂️ 256: Ability to copy paste form data between activities
  api/src/openapi/api-doc.json
  app/src/components/activity/ActivityComponent.tsx
  app/src/components/form/FormContainer.tsx
  app/src/components/form/FormControlsComponent.tsx
  app/src/features/home/activity/ActivityPage.tsx
  app/src/rjsf/business-rules/formDataCopyFields.ts
  app/src/utils/saveRetrieveFormData.ts
Labels: Form, enhancement, frontend

#263 🗺️ Fix height issue with box, map container not showing
  app/src/features/home/map/MapPage.tsx
Labels: Bug, frontend

#265 🐶🌹 Filtering activities by plant/animal type on list page
  app/src/components/activities-list/ActivitiesList.tsx
Labels: enhancement, frontend

#272 271: Autopopulate/Prefill logic required on search activity page
  app/src/components/form/FormContainer.tsx
  app/src/components/form/FormControlsComponent.tsx
  app/src/features/home/activity/ActivityPage.tsx
  app/src/features/home/search/SearchActivityPage.tsx
  app/src/utils/geometryHelpers.ts
Labels: Form, enhancement, frontend

#274 Add success and error messages to update activity
  app/src/features/home/search/SearchActivityPage.tsx
Labels: Form, enhancement, frontend

#283 ✅ Fix sonar issues :)
  api/src/paths/activity/{activityId}.ts
  api/src/paths/media.ts
  app/src/components/map/MapContainer.css
  app/src/components/map/MapContainer.tsx
  app/src/components/tabs/TabsContainer.tsx
  app/src/features/home/activity/ActivityPage.tsx
  app/src/features/home/search/SearchActivityPage.tsx
  app/src/utils/PrivateRoute.tsx
Labels: enhancement

#280 🔗 266: Link Monitorings to Treatments
  api/src/openapi/api-doc.json
  app/src/components/activities-list/ActivitiesList.tsx
  app/src/components/activities-list/ReferenceActivitiesList.tsx
  app/src/interfaces/activity-interfaces.ts
  app/src/rjsf/business-rules/populateCalculatedFields.ts
  app/src/rjsf/uiSchema/BaseUISchemaComponents.ts
  app/src/rjsf/uiSchema/RootUISchemas.ts
  app/src/utils/addActivity.ts
Labels: API, Form, enhancement, frontend

#284 Populate basic info section for monitoring created based on treatment
  app/src/components/activities-list/ReferenceActivitiesList.tsx
  app/src/utils/addActivity.ts
Labels: Form, enhancement, frontend

#286 📃 267: Populate monitoring data by treatment + 🐛 Bug fix
  api/src/openapi/api-doc.json
  api/src/paths/context/well.ts
  api/src/utils/context-queries.ts
  app/src/rjsf/business-rules/formDataCopyFields.ts
  app/src/utils/addActivity.ts
  app/src/utils/saveRetrieveFormData.ts
Labels: Bug, Form, enhancement, frontend

#289 Prettier linting fixes (FE, formatting)
  .prettierrc
  app/src/components/activities-list/ActivitiesList.tsx
  app/src/components/activities-list/ActivityListItem.tsx
  app/src/components/activities-list/ReferenceActivitiesList.tsx
  app/src/components/form/FormControlsComponent.tsx
  app/src/components/points-of-interest/ActivitiesPOI/ActivitiesPOI.tsx
  app/src/components/points-of-interest/IAPP/IAPP-Site.tsx
  app/src/contexts/NetworkContext.tsx
  app/src/features/home/activity/ActivityPage.tsx
  app/src/features/home/map/MapPage.tsx
  app/src/features/home/search/SearchActivityPage.tsx
  app/src/interfaces/activity-interfaces.ts
  app/src/rjsf/business-rules/customValidation.ts
  app/src/rjsf/business-rules/formDataCopyFields.ts
  app/src/rjsf/business-rules/populateCalculatedFields.ts
  app/src/utils/addActivity.ts
  app/src/utils/errorHandling.ts
  app/src/utils/geometryHelpers.ts
Labels: enhancement, frontend

#288 267: Populate monitoring data based on treatment
  api/src/openapi/api-doc.json
  app/src/features/home/activity/ActivityPage.tsx
  app/src/interfaces/activity-interfaces.ts
  app/src/rjsf/business-rules/formDataCopyFields.ts
  app/src/rjsf/uiSchema/RootUISchemas.ts
  app/src/rjsf/uiSchema/UISchemaComponents.ts
  app/src/utils/addActivity.ts
Labels: API, Form, enhancement, frontend

#290 Frontend linting fixes and action
  .github/workflows/lint.yml
  app/src/components/activities-list/ActivitiesList.tsx
  app/src/components/activities-list/ReferenceActivitiesList.tsx
  app/src/components/activities-search-controls/ActivitiesFilter.tsx
  app/src/components/form/FormContainer.tsx
  app/src/components/tabs/TabsContainer.tsx
  app/src/components/trip/TripDataControls.tsx
  app/src/contexts/DatabaseChangesContext.tsx
  app/src/contexts/DatabaseContext.tsx
  app/src/features/home/HomeLayout.tsx
  app/src/features/home/activity/ActivityPage.tsx
  app/src/features/home/map/MapPage.tsx
  app/src/features/home/plan/PlanPage.tsx
  app/src/features/home/references/ReferencesActivityPage.tsx
  app/src/utils/addActivity.ts
  app/src/utils/geometryHelpers.ts
Labels: Technical debt, enhancement, frontend

#291 Monitoring fields cleanup
  api/src/openapi/api-doc.json
  app/src/rjsf/uiSchema/BaseUISchemaComponents.ts
Labels: Form, frontend

#292 Lint API
  .github/workflows/lint.yml
  api/src/app.ts
  api/src/paths/activities.ts
  api/src/paths/activity.ts
  api/src/paths/activity/{activityId}.ts
  api/src/paths/context/databc/{wfs}.ts
  api/src/paths/context/elevation.ts
  api/src/paths/context/internal/{target}.ts
  api/src/paths/context/transform.ts
  api/src/paths/context/well.ts
  api/src/paths/media/{key}.ts
  api/src/paths/misc/version.ts
  api/src/paths/point-of-interest.ts
  api/src/paths/points-of-interest.ts
  api/src/queries/context-queries.ts
  api/src/utils/api-doc-security-filter.ts
  api/src/utils/auth-utils.ts
  api/src/utils/context-queries.ts
Labels: API, enhancement

#293 Lint Database
  .github/workflows/lint.yml
  database/src/migrations/20201116132439_activity_incoming_data.ts
  database/src/migrations/20201127153245_activity_incoming_data.ts
  database/src/seeds/04_add_test_users.ts
  database/src/tools/IAPP_Migrator.ts
Labels: enhancement

#295 294: Remove ability to create monitoring from my activities page
  app/src/components/activities-list/ActivitiesList.tsx
Labels: enhancement, frontend

#296 281: Link treatments to observations
  app/src/components/activities-list/ActivitiesList.tsx
  app/src/components/activities-list/ReferenceActivitiesList.tsx
  app/src/rjsf/business-rules/formDataCopyFields.ts
  app/src/rjsf/uiSchema/BaseUISchemaComponents.ts
  app/src/rjsf/uiSchema/UISchemaComponents.ts
  app/src/utils/addActivity.ts
  app/src/utils/saveRetrieveFormData.ts
Labels: Form, enhancement, frontend

#298 281: Link treatment to observation (final changes)
  api/src/openapi/api-doc.json
  app/src/components/form/FormContainer.tsx
Labels: Form, frontend

#299 268: UI for Treatment data alongside Monitoring
  api/src/openapi/api-doc.json
  app/src/components/activity/ActivityComponent.tsx
  app/src/components/photo/PhotoContainer.tsx
Labels: Form, enhancement, frontend
